name: Latest tag

on:
  push:
    branches:
      - master

jobs:
  latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"

      - name: Delete the local 'latest' tag
        run: git tag -d latest || true

      - name: Delete the remote 'latest' tag
        run: git push --delete origin latest || true

      - name: Create new 'latest' tag
        run: git tag -a latest -m "Update latest tag"

      - name: Push the 'latest' tag to Github
        run: git push origin latest
